namespace JobPortal.Domain.Entities;

/// <summary>
/// One row per (candidate, device) FCM registration token.
/// A candidate can be signed in on several devices, so tokens live in their own
/// table instead of the single CandidateProfile.FcmToken column.
/// <see cref="Token"/> is globally unique: if the same physical phone is used by
/// a different candidate later, the row is re-assigned so pushes for the previous
/// account never reach the new owner's device.
/// </summary>
public class CandidateDeviceToken
{
    public Guid DeviceTokenId { get; set; }
    public Guid CandidateId { get; set; }

    /// <summary>FCM registration token issued by Firebase for this app install.</summary>
    public string Token { get; set; } = default!;

    /// <summary>"android" | "ios" | "web" | "unknown"</summary>
    public string Platform { get; set; } = "unknown";

    /// <summary>
    /// Stable per-installation id generated by the app. Lets the API drop the
    /// previous token of the same install when Firebase rotates it.
    /// </summary>
    public string? DeviceId { get; set; }

    public string? AppVersion { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    public DateTime LastUsedAt { get; set; }

    // Navigation
    public CandidateProfile? CandidateProfile { get; set; }
}