// <auto-generated />
using System;
using JobPortal.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobPortal.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527101359_jobpostingenums")]
    partial class jobpostingenums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JobPortal.Domain.Entities.AdminSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("session_id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("char(36)")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("session_token");

                    b.Property<bool>("TrustedDevice")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("trusted_device");

                    b.HasKey("SessionId");

                    b.HasIndex("AdminId");

                    b.ToTable("admin_sessions", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("admin_id");

                    b.Property<string>("AdminIdentifier")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("admin_identifier");

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("admin_role");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by");

                    b.Property<short>("FailedAttempts")
                        .HasColumnType("smallint")
                        .HasColumnName("failed_attempts");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_until");

                    b.Property<string>("Permissions")
                        .HasColumnType("longtext")
                        .HasColumnName("permissions");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("AdminId");

                    b.HasIndex("AdminIdentifier")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionDetail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("PerformedByName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LogId");

                    b.HasIndex("PerformedBy");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateCv", b =>
                {
                    b.Property<Guid>("CvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AffindaJobId")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("AiConfidenceScore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CvFileUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("CvPdfUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("CvS3Url")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ParsedEmail")
                        .HasColumnType("longtext");

                    b.Property<int?>("ParsedExperienceYrs")
                        .HasColumnType("int");

                    b.Property<string>("ParsedName")
                        .HasColumnType("longtext");

                    b.Property<string>("ParsedPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("ParsedSkills")
                        .HasColumnType("longtext");

                    b.Property<string>("ParsedTrade")
                        .HasColumnType("longtext");

                    b.HasKey("CvId");

                    b.HasIndex("CandidateId");

                    b.ToTable("candidate_cv", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateEducation", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InstituteName")
                        .HasColumnType("longtext");

                    b.Property<string>("MarksPercentage")
                        .HasColumnType("longtext");

                    b.Property<short?>("PassoutYear")
                        .HasColumnType("smallint");

                    b.HasKey("EducationId");

                    b.HasIndex("CandidateId");

                    b.ToTable("candidate_education", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateProfile", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("candidate_id");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("longtext")
                        .HasColumnName("admin_notes");

                    b.Property<byte?>("AiMatchScore")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("ai_match_score");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("availability_status");

                    b.Property<DateTime?>("AvailabilityUpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("availability_updated_at");

                    b.Property<string>("Band")
                        .HasColumnType("longtext")
                        .HasColumnName("band");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("CreditBalance")
                        .HasColumnType("int")
                        .HasColumnName("credit_balance");

                    b.Property<string>("CurrentCity")
                        .HasColumnType("longtext")
                        .HasColumnName("current_city");

                    b.Property<string>("CurrentState")
                        .HasColumnType("longtext")
                        .HasColumnName("current_state");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DisabilityNote")
                        .HasColumnType("longtext")
                        .HasColumnName("disability_note");

                    b.Property<bool>("DisabilityStatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disability_status");

                    b.Property<string>("FcmToken")
                        .HasColumnType("longtext")
                        .HasColumnName("fcm_token");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<bool>("ItiCertified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("iti_certified");

                    b.Property<string>("ItiCollege")
                        .HasColumnType("longtext")
                        .HasColumnName("iti_college");

                    b.Property<string>("ItiMarks")
                        .HasColumnType("longtext")
                        .HasColumnName("iti_marks");

                    b.Property<string>("ItiTrade")
                        .HasColumnType("longtext")
                        .HasColumnName("iti_trade");

                    b.Property<DateTime?>("LastAppliedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_applied_at");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext")
                        .HasColumnName("nationality");

                    b.Property<bool>("NewsletterOptIn")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("newsletter_opt_in");

                    b.Property<int?>("PreferredSalary")
                        .HasColumnType("int")
                        .HasColumnName("preferred_salary");

                    b.Property<string>("PreferredWorkLocation")
                        .HasColumnType("longtext")
                        .HasColumnName("preferred_work_location");

                    b.Property<string>("PrimaryTrade")
                        .HasColumnType("longtext")
                        .HasColumnName("primary_trade");

                    b.Property<byte>("ProfileCompletionPct")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("profile_completion_pct");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("profile_photo_url");

                    b.Property<string>("ProfileStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("profile_status");

                    b.Property<string>("ReengagementResponse")
                        .HasColumnType("longtext")
                        .HasColumnName("reengagement_response");

                    b.Property<bool>("TempPasswordFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("temp_password_flag");

                    b.Property<int>("TotalExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("total_experience_years");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<bool>("WelcomeEmailSent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("welcome_email_sent");

                    b.HasKey("CandidateId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("candidate_profiles", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateSkill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SkillRole")
                        .HasColumnType("longtext");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte?>("YearsOfExperience")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("SkillId");

                    b.HasIndex("CandidateId");

                    b.ToTable("candidate_skills", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateUnlock", b =>
                {
                    b.Property<Guid>("UnlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CandidateProfileCandidateId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("CreditsDeducted")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("CvWatermarkEmployerId")
                        .HasColumnType("longtext");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployerProfileEmployerId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("UnlockExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("UnlockRequestedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("UnlockStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UnlockTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WalletBalanceAfter")
                        .HasColumnType("int");

                    b.Property<int>("WalletBalanceBefore")
                        .HasColumnType("int");

                    b.Property<string>("WatermarkedCvUrl")
                        .HasColumnType("longtext");

                    b.HasKey("UnlockId");

                    b.HasIndex("CandidateProfileCandidateId");

                    b.HasIndex("EmployerProfileEmployerId");

                    b.HasIndex("EmployerId", "CandidateId")
                        .IsUnique();

                    b.ToTable("candidate_unlocks", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateWorkHistory", b =>
                {
                    b.Property<Guid>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOffshore")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("WorkLocation")
                        .HasColumnType("longtext");

                    b.HasKey("WorkId");

                    b.HasIndex("CandidateId");

                    b.ToTable("candidate_work_history", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.ConsentLog", b =>
                {
                    b.Property<Guid>("ConsentLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("ConsentGiven")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ConsentTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConsentVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataResidency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NationalIdStorage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("ConsentLogId");

                    b.HasIndex("UserId");

                    b.ToTable("consent_logs", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CountryVerificationConfig", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AcceptedCandidateIdTypes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AcceptedEmployerDocTypes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ConfigUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ConfigUpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PrimaryBusinessVerify")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("RequireSecurityDeposit")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ConfigId");

                    b.HasIndex("ConfigUpdatedBy");

                    b.HasIndex("CountryCode")
                        .IsUnique();

                    b.ToTable("country_verification_config", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CreditWallet", b =>
                {
                    b.Property<Guid>("Wallet_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("wallet_id");

                    b.Property<int>("CreditBalance")
                        .HasColumnType("int")
                        .HasColumnName("credit_balance");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employer_id");

                    b.Property<DateTime?>("PackExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("pack_expires_at");

                    b.Property<string>("PackageName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("package_name");

                    b.Property<bool>("SharedWallet")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("shared_wallet");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Wallet_Id");

                    b.HasIndex("EmployerId")
                        .IsUnique();

                    b.ToTable("credit_wallets", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.Dispute", b =>
                {
                    b.Property<Guid>("DisputeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DisputeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RaisedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DisputeId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("RaisedBy");

                    b.ToTable("disputes", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.EmployerBadge", b =>
                {
                    b.Property<Guid>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("BadgeBlueTick")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BadgeGstVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("BadgeIssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("BadgePanVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BadgePoeLicensed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BadgeRevocationReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("BadgeRevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("BadgeRpslLicensed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BadgeStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BadgeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("BlueTickEligible")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IssuedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("BadgeId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("IssuedBy");

                    b.ToTable("employer_badges", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.EmployerNotificationSetting", b =>
                {
                    b.Property<Guid>("NotifPrefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("notif_pref_id");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("employer_id");

                    b.Property<string>("FcmToken")
                        .HasColumnType("longtext")
                        .HasColumnName("fcm_token");

                    b.Property<bool>("PrefApplicantNotify")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pref_applicant_notify");

                    b.Property<bool>("PrefAvailabilityPush")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pref_availability_push");

                    b.Property<bool>("PrefCreditExpiryEmail")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pref_credit_expiry_email");

                    b.Property<bool>("PrefEmailEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pref_email_enabled");

                    b.Property<bool>("PrefPushEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pref_push_enabled");

                    b.Property<short>("SessionTimeoutMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("session_timeout_minutes");

                    b.HasKey("NotifPrefId");

                    b.HasIndex("EmployerId")
                        .IsUnique();

                    b.ToTable("employer_notification_settings", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.EmployerProfile", b =>
                {
                    b.Property<Guid>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("employer_id");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int")
                        .HasColumnName("account_status");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longtext")
                        .HasColumnName("address_line2");

                    b.Property<string>("BusinessRegDocUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("business_reg_doc_url");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("business_type");

                    b.Property<string>("Cin")
                        .HasColumnType("longtext")
                        .HasColumnName("cin");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("company_description");

                    b.Property<string>("CompanyDisplayName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("company_display_name");

                    b.Property<string>("CompanyLogoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("company_logo_url");

                    b.Property<string>("CompanySize")
                        .HasColumnType("longtext")
                        .HasColumnName("company_size");

                    b.Property<DateTime?>("ConsentTimestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("consent_timestamp");

                    b.Property<string>("ContactEmailPublic")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_email_public");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contact_person_name");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("designation");

                    b.Property<bool>("GstRegistered")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("gst_registered");

                    b.Property<string>("Gstn")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gstn");

                    b.Property<DateOnly?>("GstnRegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("gstn_registration_date");

                    b.Property<string>("IndustryType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("industry_type");

                    b.Property<string>("KarzaRequestId")
                        .HasColumnType("longtext")
                        .HasColumnName("karza_request_id");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("legal_name");

                    b.Property<string>("OfficeAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("office_address");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("longtext")
                        .HasColumnName("operating_hours");

                    b.Property<string>("Pan")
                        .HasColumnType("longtext")
                        .HasColumnName("pan");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pincode");

                    b.Property<string>("PoeCompanyName")
                        .HasColumnType("longtext")
                        .HasColumnName("poe_company_name");

                    b.Property<bool>("PoeExpiredFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("poe_expired_flag");

                    b.Property<string>("PoeLicenceNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("poe_licence_number");

                    b.Property<string>("PoeLicenceS3Url")
                        .HasColumnType("longtext")
                        .HasColumnName("poe_licence_s3_url");

                    b.Property<DateOnly?>("PoeValidityDate")
                        .HasColumnType("date")
                        .HasColumnName("poe_validity_date");

                    b.Property<byte>("ProfileCompletionScore")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("profile_completion_score");

                    b.Property<string>("RpslCompanyName")
                        .HasColumnType("longtext")
                        .HasColumnName("rpsl_company_name");

                    b.Property<bool>("RpslExpiredFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("rpsl_expired_flag");

                    b.Property<string>("RpslLicenceNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("rpsl_licence_number");

                    b.Property<string>("RpslLicenceS3Url")
                        .HasColumnType("longtext")
                        .HasColumnName("rpsl_licence_s3_url");

                    b.Property<DateOnly?>("RpslValidityDate")
                        .HasColumnType("date")
                        .HasColumnName("rpsl_validity_date");

                    b.Property<bool>("SecurityDepositPaid")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("security_deposit_paid");

                    b.Property<string>("SecurityDepositStatus")
                        .HasColumnType("longtext")
                        .HasColumnName("security_deposit_status");

                    b.Property<string>("State")
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.Property<string>("Tags")
                        .HasColumnType("longtext")
                        .HasColumnName("tags");

                    b.Property<string>("TradeName")
                        .HasColumnType("longtext")
                        .HasColumnName("trade_name");

                    b.Property<DateTime?>("TrialExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("trial_expires_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("website_url");

                    b.Property<short?>("YearEstablished")
                        .HasColumnType("smallint")
                        .HasColumnName("year_established");

                    b.HasKey("EmployerId");

                    b.HasIndex("Gstn")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("employer_profiles", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.EmployerSubUser", b =>
                {
                    b.Property<Guid>("SubUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CanManageApplications")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanPostJobs")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanSearchCandidates")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanUnlockProfiles")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("InviteAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("InviteExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("InviteToken")
                        .HasColumnType("char(36)");

                    b.Property<string>("SubUserEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubUserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubUserRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubUserStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("SubUserId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("UserId");

                    b.ToTable("employer_sub_users", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InvoiceAmount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<int>("InvoiceGst")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("InvoiceS3Url")
                        .HasColumnType("longtext");

                    b.Property<int>("InvoiceTotal")
                        .HasColumnType("int");

                    b.Property<Guid>("PaymentTransactionTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("PaymentTransactionTransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.ItiCertificateReview", b =>
                {
                    b.Property<Guid>("ItiReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdminNote")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("AiConfidenceScore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AiExtractedCertNo")
                        .HasColumnType("longtext");

                    b.Property<string>("AiExtractedInstitute")
                        .HasColumnType("longtext");

                    b.Property<string>("AiExtractedTrade")
                        .HasColumnType("longtext");

                    b.Property<short?>("AiExtractedYear")
                        .HasColumnType("smallint");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItiCertImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ItiReviewId");

                    b.HasIndex("CandidateId");

                    b.ToTable("iti_certificate_reviews", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EmployerInternalNote")
                        .HasColumnType("longtext");

                    b.Property<Guid>("JobId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("PassportGatePassed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RejectionAutoNotify")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("StatusChangedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("StatusUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ViewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("WithdrawalAllowed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ApplicationId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("JobId", "CandidateId")
                        .IsUnique();

                    b.ToTable("job_applications", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.JobPosting", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte?>("AgeMax")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("AgeMin")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateOnly>("ApplicationDeadline")
                        .HasColumnType("date");

                    b.Property<int>("AppliedCount")
                        .HasColumnType("int");

                    b.Property<int>("CompanyVisibility")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<bool>("DisabilityEligible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EducationRequired")
                        .HasColumnType("longtext");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("char(36)");

                    b.Property<byte>("ExperienceRequiredYears")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("GenderPreferred")
                        .HasColumnType("int");

                    b.Property<bool>("IsInternational")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KeySkills")
                        .HasColumnType("longtext");

                    b.Property<string>("LanguageRequired")
                        .HasColumnType("longtext");

                    b.Property<int>("LastCompletedStep")
                        .HasColumnType("int");

                    b.Property<string>("LicenceDocsRequired")
                        .HasColumnType("longtext");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.Property<string>("OffshoreRegion")
                        .HasColumnType("longtext");

                    b.Property<string>("OffshoreVesselName")
                        .HasColumnType("longtext");

                    b.Property<string>("OnshoreCity")
                        .HasColumnType("longtext");

                    b.Property<string>("OnshoreState")
                        .HasColumnType("longtext");

                    b.Property<bool>("PassportRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte?>("PassportValidityMonths")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid?>("PostedBySubUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PublishingTags")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<int>("SalaryCurrency")
                        .HasColumnType("int");

                    b.Property<int>("SalaryDisplayOption")
                        .HasColumnType("int");

                    b.Property<int>("SalaryMax")
                        .HasColumnType("int");

                    b.Property<int>("SalaryMin")
                        .HasColumnType("int");

                    b.Property<string>("ScreeningQuestions")
                        .HasColumnType("longtext");

                    b.Property<string>("TradeCategory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<short>("Vacancies")
                        .HasColumnType("smallint");

                    b.HasKey("JobId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("PostedBySubUserId");

                    b.ToTable("job_postings", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.KycVerification", b =>
                {
                    b.Property<Guid>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdminDecision")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("AiConfidenceScore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AiExtractedAddress")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("AiExtractedDob")
                        .HasColumnType("date");

                    b.Property<string>("AiExtractedName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IdBackImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("IdFrontImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("OcrConfidence")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("VerificationId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("kyc_verifications", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.OtpVerification", b =>
                {
                    b.Property<Guid>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("otp_id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("country_code");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_verified");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_until");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mobile_number");

                    b.Property<byte>("OtpAttempts")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("otp_attempts");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("otp_code");

                    b.Property<DateTime>("OtpExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("otp_expires_at");

                    b.Property<DateTime>("OtpSentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("otp_sent_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ResendCooldownSec")
                        .HasColumnType("int")
                        .HasColumnName("resend_cooldown_sec");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("OtpId");

                    b.HasIndex("UserId");

                    b.ToTable("otp_verifications", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.PassportVerification", b =>
                {
                    b.Property<Guid>("PassportVerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AdminDecision")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("AiConfidenceScore")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly?>("AiExtractedExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("AiExtractedFullName")
                        .HasColumnType("longtext");

                    b.Property<string>("AiExtractedNationality")
                        .HasColumnType("longtext");

                    b.Property<string>("AiExtractedPassportNo")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ExpiryAutoFlagged")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PassportImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("PassportVerId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("passport_verifications", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmountPaise")
                        .HasColumnType("int");

                    b.Property<Guid?>("CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CandidateProfileCandidateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreditQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreditsAddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("EmployerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EmployerProfileEmployerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("GatewayRefundId")
                        .HasColumnType("longtext");

                    b.Property<int>("GstAmountPaise")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceUrl")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OriginalTxnId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PackType")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RazorpayOrderId")
                        .HasColumnType("longtext");

                    b.Property<string>("RazorpayPaymentId")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("RefundProcessedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("RefundReason")
                        .HasColumnType("longtext");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalAmountPaise")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<byte?>("ValidityMonths")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("TransactionId");

                    b.HasIndex("CandidateProfileCandidateId");

                    b.HasIndex("EmployerProfileEmployerId");

                    b.HasIndex("OriginalTxnId");

                    b.HasIndex("RefundProcessedBy");

                    b.HasIndex("UserId");

                    b.ToTable("payment_transactions", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.PlatformConfig", b =>
                {
                    b.Property<Guid>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AlertChannels")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreditExpiryAlertDays")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("CvUnlockValidityDays")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("FcmFallbackEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("OneTrialPerGstDomain")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReengagementChannel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("ReengagementIntervalDays")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("TrialCvDownloadAllowed")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("TrialDurationDays")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("TrialFreeCredits")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("WatermarkTemplate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WhatsappTemplateId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ConfigId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("platform_config", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.RegistrationSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longtext");

                    b.Property<string>("BusinessType")
                        .HasColumnType("longtext");

                    b.Property<string>("Cin")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyLogoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanySize")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPersonEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("longtext");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("GstRegistered")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Gstn")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("GstnRegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("IndustryType")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LastCompletedStep")
                        .HasColumnType("int");

                    b.Property<string>("LegalName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LicencesSkipped")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("MobileVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Pan")
                        .HasColumnType("longtext");

                    b.Property<string>("Pincode")
                        .HasColumnType("longtext");

                    b.Property<string>("PoeLicenceS3Url")
                        .HasColumnType("longtext");

                    b.Property<bool>("RequiresSecurityDeposit")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RpslLicenceS3Url")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("TradeName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("longtext");

                    b.HasKey("SessionId");

                    b.ToTable("registration_sessions", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.SavedJob", b =>
                {
                    b.Property<Guid>("SavedJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CandidateProfileCandidateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("JobPostingJobId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("SavedJobId");

                    b.HasIndex("CandidateProfileCandidateId");

                    b.HasIndex("JobPostingJobId");

                    b.HasIndex("CandidateId", "JobId")
                        .IsUnique();

                    b.ToTable("saved_jobs", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.SavedSearch", b =>
                {
                    b.Property<Guid>("SavedSearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AlertEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployerProfileEmployerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SavedSearchName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SearchFilters")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SavedSearchId");

                    b.HasIndex("EmployerProfileEmployerId");

                    b.ToTable("saved_searches", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.SecurityDeposit", b =>
                {
                    b.Property<Guid>("DepositId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AmountPaise")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DepositStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EmployerProfileEmployerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PaymentTransactionTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DepositId");

                    b.HasIndex("EmployerId")
                        .IsUnique();

                    b.HasIndex("EmployerProfileEmployerId");

                    b.HasIndex("PaymentTransactionTransactionId");

                    b.ToTable("security_deposits", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.SupportTicket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RaisedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TicketId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("RaisedBy");

                    b.ToTable("support_tickets", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("Pending")
                        .HasColumnName("account_status");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("+91")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("KycStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("Pending")
                        .HasColumnName("kyc_status");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("Unpaid")
                        .HasColumnName("payment_status");

                    b.Property<string>("SuspensionReason")
                        .HasColumnType("longtext")
                        .HasColumnName("suspension_reason");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_type");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.HasIndex("MobileNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_users_mobile");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.AdminSession", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.AdminUser", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("JobPortal.Domain.Entities.AdminUser", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.AdminUser", "PerformedByAdmin")
                        .WithMany()
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedByAdmin");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateCv", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany("Cvs")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateEducation", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany("Educations")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateProfile", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("JobPortal.Domain.Entities.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateSkill", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany("Skills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateUnlock", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateProfileCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Domain.Entities.EmployerProfile", "EmployerProfile")
                        .WithMany()
                        .HasForeignKey("EmployerProfileEmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("EmployerProfile");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateWorkHistory", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany("WorkHistories")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.ConsentLog", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CountryVerificationConfig", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.AdminUser", "UpdatedByAdmin")
                        .WithMany()
                        .HasForeignKey("ConfigUpdatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CreditWallet", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.EmployerProfile", "EmployerProfile")
                        .WithOne("CreditWallet")
                        .HasForeignKey("JobPortal.Domain.Entities.CreditWallet", "EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployerProfile");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.Dispute", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.AdminUser", "AssignedAdmin")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobPortal.Domain.Entities.User", "RaisedByUser")
                        .WithMany()
                        .HasForeignKey("RaisedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedAdmin");

                    b.Navigation("RaisedByUser");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.EmployerBadge", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.EmployerProfile", "EmployerProfile")
                        .WithMany("Badges")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Domain.Entities.AdminUser", "IssuedByAdmin")
                        .WithMany()
                        .HasForeignKey("IssuedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployerProfile");

                    b.Navigation("IssuedByAdmin");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.EmployerNotificationSetting", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.EmployerProfile", "EmployerProfile")
                        .WithOne("NotificationSetting")
                        .HasForeignKey("JobPortal.Domain.Entities.EmployerNotificationSetting", "EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployerProfile");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.EmployerProfile", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("JobPortal.Domain.Entities.EmployerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.EmployerSubUser", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.EmployerProfile", "EmployerProfile")
                        .WithMany("SubUsers")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployerProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany()
                        .HasForeignKey("PaymentTransactionTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentTransaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.ItiCertificateReview", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.JobApplication", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Domain.Entities.EmployerProfile", "EmployerProfile")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("EmployerProfile");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.JobPosting", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.EmployerProfile", "EmployerProfile")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Domain.Entities.EmployerSubUser", "PostedBySubUser")
                        .WithMany()
                        .HasForeignKey("PostedBySubUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EmployerProfile");

                    b.Navigation("PostedBySubUser");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.KycVerification", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Domain.Entities.AdminUser", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CandidateProfile");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.Notification", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.OtpVerification", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.User", "User")
                        .WithMany("OtpVerifications")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.PassportVerification", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Domain.Entities.AdminUser", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CandidateProfile");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateProfileCandidateId");

                    b.HasOne("JobPortal.Domain.Entities.EmployerProfile", "EmployerProfile")
                        .WithMany()
                        .HasForeignKey("EmployerProfileEmployerId");

                    b.HasOne("JobPortal.Domain.Entities.PaymentTransaction", "OriginalTransaction")
                        .WithMany()
                        .HasForeignKey("OriginalTxnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JobPortal.Domain.Entities.AdminUser", "RefundAdmin")
                        .WithMany()
                        .HasForeignKey("RefundProcessedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobPortal.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("EmployerProfile");

                    b.Navigation("OriginalTransaction");

                    b.Navigation("RefundAdmin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.PlatformConfig", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.AdminUser", "UpdatedByAdmin")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdatedByAdmin");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.SavedJob", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.CandidateProfile", "CandidateProfile")
                        .WithMany()
                        .HasForeignKey("CandidateProfileCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany()
                        .HasForeignKey("JobPostingJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.SavedSearch", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.EmployerProfile", "EmployerProfile")
                        .WithMany()
                        .HasForeignKey("EmployerProfileEmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployerProfile");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.SecurityDeposit", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.EmployerProfile", "EmployerProfile")
                        .WithMany()
                        .HasForeignKey("EmployerProfileEmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobPortal.Domain.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany()
                        .HasForeignKey("PaymentTransactionTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployerProfile");

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.SupportTicket", b =>
                {
                    b.HasOne("JobPortal.Domain.Entities.AdminUser", "AssignedAdmin")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JobPortal.Domain.Entities.User", "RaisedByUser")
                        .WithMany()
                        .HasForeignKey("RaisedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedAdmin");

                    b.Navigation("RaisedByUser");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.CandidateProfile", b =>
                {
                    b.Navigation("Cvs");

                    b.Navigation("Educations");

                    b.Navigation("Skills");

                    b.Navigation("WorkHistories");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.EmployerProfile", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("CreditWallet");

                    b.Navigation("NotificationSetting");

                    b.Navigation("SubUsers");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.JobPosting", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("JobPortal.Domain.Entities.User", b =>
                {
                    b.Navigation("OtpVerifications");
                });
#pragma warning restore 612, 618
        }
    }
}
