using System.ComponentModel.DataAnnotations;

namespace JobPortal.Application.DTOs.Candidate.Push;

// POST /api/candidate/device-tokens
public class RegisterDeviceTokenRequestDto
{
    [Required]
    [StringLength(512, MinimumLength = 20)]
    public string FcmToken { get; set; } = string.Empty;

    /// <summary>android | ios | web</summary>
    [StringLength(20)]
    public string? Platform { get; set; }

    /// <summary>Stable per-install id generated by the app (UUID).</summary>
    [StringLength(200)]
    public string? DeviceId { get; set; }

    [StringLength(50)]
    public string? AppVersion { get; set; }
}

// POST /api/candidate/device-tokens/unregister
public class UnregisterDeviceTokenRequestDto
{
    [Required]
    [StringLength(512, MinimumLength = 20)]
    public string FcmToken { get; set; } = string.Empty;
}

public class DeviceTokenResponseDto
{
    public bool Success { get; set; }
    public string Message { get; set; } = string.Empty;
}